### PR TITLE
Performance CI and refactoring

### PR DESCRIPTION
**Pull request by kpamnany**
Added:
- Test set is now specified in `CLIMA/slurmci-test.toml`.
- Performance tests are specified in `CLIMA/slurmci-perf.toml`.
- https://github.com/climate-machine/CLIMA/pull/449 therefore has to be merged before this can be.
- Branches to test are also specified on the command line.
- State is stored in `slurmci.cache` as a serialized `Dict` rather than in a branches subdirectory.
- All job scripts are now here, in `scripts/`.
- Search for `*.nvprof` files in log directories; if present, parse them and upload a gist with some performance graphs.
- Also parse metrics files generated by `nvprof`.
- Store performance data in a SQLITE database.
- Generate performance diffs for kernels across commits.

TODO:
- More testing.
- Will probably defer: finalizing as a job at the end is very vulnerable to failures. The main script itself should poll on job state and cleanup. However, that can leave it running for quite a long time.

### CODE REVIEW

**Comment by simonbyrne** [comment]
>     * Cleanup: there are no clean interfaces between cron, finalize and the module. Finalizing as a job at the end is very vulnerable to failures. cron itself should poll on job state and cleanup.

Why would it be vulnerable to failures? I have it set to run `afterany`.

**Comment by kpamnany** [comment]
SLURM itself goes down. The job controller can get overloaded and time out. When cleanup doesn't run, the status isn't updated on Github and the download and build aren't cleaned up. You can find a couple such leftovers in your scratchio.

**Comment by simonbyrne** [comment]
ah, fair enough

**Comment by kpamnany** [comment]
I'm thinking of only completing the first couple of TODOs in this PR, saving the third refactoring for a new PR. Thoughts?

**Comment by simonbyrne** [comment]
Up to you. I'll move the repo to CliMA so you can have commit access.

**Pull request merged**
